import C from '../config/colors.config';

const personaBrown = '#C28A5C';
const personaBrownSoft = '#E0A875';
const personaBrownFaint = 'rgba(194, 138, 92, 0.1)';
const personaBrownBorder = 'rgba(194, 138, 92, 0.42)';

const settingsStyles = {
  modalHost: {
    flex: 1,
    backgroundColor: '#0A0A0F',
  },
  modalBackdrop: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  modalContent: {
    flex: 1,
    backgroundColor: C.bgMain,
    borderWidth: 1,
    borderColor: '#222235',
    borderRadius: 18,
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#1E1E2C',
    backgroundColor: '#0F0F16',
  },
  modalHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  modalHeaderIconBox: {
    width: 34,
    height: 34,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(123, 47, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(123, 47, 255, 0.3)',
  },
  modalTitleBlock: {
    justifyContent: 'center',
  },
  modalSubtitle: {
    fontSize: 10,
    color: '#8A8A9D',
    marginTop: 1,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  modalCloseBtn: {
    width: 34,
    height: 34,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(123, 47, 255, 0.08)',
    shadowColor: C.purple,
    shadowOpacity: 0.35,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 0 },
    elevation: 8,
  },
  modalBody: {
    padding: 12,
  },
  modalBodyContent: {
    flexGrow: 1,
    paddingTop: 32,
    paddingBottom: 24,
  },
  settingsSection: {
    marginBottom: 24,
    borderBottomWidth: 1,
    borderBottomColor: '#1E1E2C',
    paddingBottom: 24,
  },
  apiPanelToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#11111A',
    borderWidth: 1,
    borderColor: '#242436',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 22,
  },
  apiPanelToggleOpen: {
    borderColor: 'rgba(123, 47, 255, 0.45)',
    backgroundColor: '#13131F',
  },
  profilePanelToggleOpen: {
    borderColor: 'rgba(123, 47, 255, 0.45)',
    backgroundColor: '#13131F',
  },
  personaPanelToggleOpen: {
    borderColor: 'rgba(194, 138, 92, 0.55)',
    backgroundColor: 'rgba(194, 138, 92, 0.07)',
  },
  apiPanelToggleLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    flex: 1,
  },
  apiPanelIconBox: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(123, 47, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(123, 47, 255, 0.35)',
    flexShrink: 0,
  },
  securityIconBox: {
    backgroundColor: 'rgba(123, 47, 255, 0.08)',
    borderColor: 'rgba(123, 47, 255, 0.32)',
  },
  aboutIconBox: {
    backgroundColor: 'rgba(123, 47, 255, 0.08)',
    borderColor: 'rgba(123, 47, 255, 0.32)',
  },
  profileIconBox: {
    backgroundColor: 'rgba(123, 47, 255, 0.1)',
    borderColor: 'rgba(123, 47, 255, 0.35)',
  },
  personaIconBox: {
    backgroundColor: personaBrownFaint,
    borderColor: personaBrownBorder,
  },
  lockIconBox: {
    backgroundColor: 'rgba(123, 47, 255, 0.08)',
    borderColor: 'rgba(123, 47, 255, 0.34)',
  },
  passwordManagerToggle: {},
  passwordManagerToggleOpen: {
    borderColor: 'rgba(123, 47, 255, 0.55)',
    backgroundColor: 'rgba(123, 47, 255, 0.06)',
  },
  privacyPanelToggleOpen: {
    borderColor: 'rgba(123, 47, 255, 0.5)',
    backgroundColor: 'rgba(123, 47, 255, 0.06)',
  },
  aboutPanelToggleOpen: {
    borderColor: 'rgba(123, 47, 255, 0.55)',
    backgroundColor: 'rgba(123, 47, 255, 0.06)',
  },
  passwordManagerIconBox: {
    backgroundColor: 'rgba(123, 47, 255, 0.08)',
    borderColor: 'rgba(123, 47, 255, 0.34)',
  },
  resetIconBox: {
    backgroundColor: 'rgba(239, 68, 68, 0.08)',
    borderColor: 'rgba(239, 68, 68, 0.32)',
  },
  resetPanelToggleOpen: {
    borderColor: 'rgba(239, 68, 68, 0.45)',
    backgroundColor: '#151118',
  },
  apiPanelTitle: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 2,
  },
  apiPanelSub: {
    color: '#8A8A9D',
    fontSize: 10,
    marginTop: 3,
  },
  apiPanelStatePill: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 7,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: '#333344',
  },
  apiPanelStatePillOpen: {
    backgroundColor: 'rgba(123, 47, 255, 0.1)',
    borderColor: 'rgba(123, 47, 255, 0.45)',
  },
  profilePanelStatePillOpen: {
    backgroundColor: 'rgba(123, 47, 255, 0.12)',
    borderColor: 'rgba(123, 47, 255, 0.45)',
  },
  personaPanelStatePillOpen: {
    backgroundColor: 'rgba(194, 138, 92, 0.14)',
    borderColor: 'rgba(194, 138, 92, 0.52)',
  },
  resetPanelStatePillOpen: {
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    borderColor: 'rgba(239, 68, 68, 0.45)',
  },
  apiPanelStateText: {
    color: '#8A8A9D',
    fontSize: 8,
    fontWeight: '900',
  },
  apiPanelStateTextOpen: {
    color: C.purpleSoft,
  },
  profilePanelStateTextOpen: {
    color: C.purpleSoft,
  },
  personaPanelStateTextOpen: {
    color: personaBrownSoft,
  },
  passwordManagerStatePillOpen: {
    backgroundColor: 'rgba(123, 47, 255, 0.1)',
    borderColor: 'rgba(123, 47, 255, 0.45)',
  },
  passwordManagerStateTextOpen: {
    color: C.purpleSoft,
  },
  aboutPanelStatePillOpen: {
    backgroundColor: 'rgba(123, 47, 255, 0.1)',
    borderColor: 'rgba(123, 47, 255, 0.45)',
  },
  aboutPanelStateTextOpen: {
    color: C.purpleSoft,
  },
  resetPanelStateTextOpen: {
    color: '#EF4444',
  },
  sectionHeader: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FFFFFF',
    marginBottom: 6,
    letterSpacing: 0.2,
  },
  sectionDesc: {
    fontSize: 11,
    color: '#8A8A9D',
    lineHeight: 16,
    marginBottom: 16,
  },
  infoPanel: {
    backgroundColor: '#0C0C12',
    borderWidth: 1,
    borderColor: '#20202F',
    borderRadius: 12,
    padding: 14,
    marginTop: -4,
    marginBottom: 16,
  },
  infoPanelTitle: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 6,
  },
  infoPanelText: {
    color: '#A8A8B8',
    fontSize: 11,
    lineHeight: 16,
    marginBottom: 14,
  },
  personaSettingsPanel: {
    backgroundColor: '#0F0D0B',
    borderWidth: 1,
    borderColor: 'rgba(194, 138, 92, 0.18)',
    borderRadius: 12,
    padding: 14,
    marginTop: -4,
    marginBottom: 16,
  },
  personaSettingsHero: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: 'rgba(194, 138, 92, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(194, 138, 92, 0.26)',
    borderRadius: 12,
    padding: 12,
    marginBottom: 14,
  },
  personaSettingsIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#11111A',
    borderWidth: 1,
    borderColor: personaBrownBorder,
    flexShrink: 0,
  },
  personaSettingsTitle: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
  },
  personaSettingsSub: {
    color: '#A8A8B8',
    fontSize: 10,
    lineHeight: 14,
    marginTop: 3,
  },
  personaActivePill: {
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: 'rgba(194, 138, 92, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(194, 138, 92, 0.44)',
  },
  personaActivePillText: {
    color: personaBrownSoft,
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 0.45,
  },
  personaModeBubbleWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  personaModeBubble: {
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    backgroundColor: '#12100E',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 999,
    paddingLeft: 10,
    paddingRight: 7,
    paddingVertical: 6,
  },
  personaModeBubbleActive: {
    backgroundColor: 'rgba(194, 138, 92, 0.14)',
    borderColor: 'rgba(194, 138, 92, 0.58)',
  },
  personaModeDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
    backgroundColor: '#4B4038',
  },
  personaModeDotActive: {
    backgroundColor: personaBrownSoft,
    shadowColor: personaBrown,
    shadowOpacity: 0.4,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 0 },
    elevation: 4,
  },
  personaModeBubbleText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '800',
  },
  personaModeBubbleTextActive: {
    color: '#FFE2C2',
  },
  personaModeState: {
    minWidth: 28,
    alignItems: 'center',
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  personaModeStateActive: {
    backgroundColor: 'rgba(194, 138, 92, 0.18)',
    borderColor: 'rgba(194, 138, 92, 0.52)',
  },
  personaModeStateText: {
    color: '#8A8A9D',
    fontSize: 7,
    fontWeight: '900',
  },
  personaModeStateTextActive: {
    color: personaBrownSoft,
  },
  personaModeActiveCard: {
    backgroundColor: 'rgba(194, 138, 92, 0.07)',
    borderWidth: 1,
    borderColor: 'rgba(194, 138, 92, 0.2)',
    borderRadius: 10,
    padding: 10,
    marginTop: 10,
  },
  personaModeActiveLabel: {
    color: personaBrownSoft,
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 0.4,
    marginBottom: 4,
  },
  personaModeActiveText: {
    color: '#C9B7A8',
    fontSize: 10,
    lineHeight: 14,
  },
  clearDataBtn: {
    backgroundColor: 'rgba(239, 68, 68, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.25)',
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  clearDataBtnText: {
    color: '#EF4444',
    fontSize: 12,
    fontWeight: '700',
  },
  complianceBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: 'rgba(123, 47, 255, 0.06)',
    borderWidth: 1,
    borderColor: 'rgba(123, 47, 255, 0.2)',
    borderRadius: 12,
    padding: 14,
    marginBottom: 20,
    gap: 10,
  },
  complianceIcon: {
    display: 'none',
    fontSize: 18,
    marginTop: 1,
  },
  complianceIconBox: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(123, 47, 255, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(123, 47, 255, 0.28)',
    flexShrink: 0,
  },
  complianceText: {
    flex: 1,
    fontSize: 11,
    color: '#C4B5FD',
    lineHeight: 16,
    fontWeight: '500',
  },
  passwordPanel: {
    backgroundColor: '#0C0C12',
    borderWidth: 1,
    borderColor: '#20202F',
    borderRadius: 12,
    padding: 14,
    marginTop: -4,
    marginBottom: 16,
  },
  passwordPanelHero: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: 'rgba(123, 47, 255, 0.06)',
    borderWidth: 1,
    borderColor: 'rgba(123, 47, 255, 0.22)',
    borderRadius: 12,
    padding: 12,
    marginBottom: 14,
  },
  passwordHeroIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#11111A',
    borderWidth: 1,
    borderColor: 'rgba(123, 47, 255, 0.34)',
  },
  passwordPanelTitle: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
  },
  passwordPanelSub: {
    color: '#A8A8B8',
    fontSize: 10,
    lineHeight: 14,
    marginTop: 3,
  },
  passwordFieldBlock: {
    marginBottom: 0,
  },
  passwordInputShell: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#050508',
    borderWidth: 1,
    borderColor: '#1E1E2C',
    borderRadius: 8,
    marginBottom: 12,
  },
  passwordInputError: {
    borderColor: 'rgba(239, 68, 68, 0.72)',
    backgroundColor: 'rgba(239, 68, 68, 0.04)',
  },
  passwordTextInput: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
    color: '#FFFFFF',
    fontSize: 12,
  },
  passwordEyeBtn: {
    width: 40,
    alignSelf: 'stretch',
    alignItems: 'center',
    justifyContent: 'center',
  },
  passwordRemoveBtn: {
    backgroundColor: 'rgba(239, 68, 68, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.32)',
    borderRadius: 10,
    padding: 12,
    marginTop: 10,
  },
  passwordRemoveTitle: {
    color: '#EF4444',
    fontSize: 12,
    fontWeight: '900',
  },
  passwordRemoveSub: {
    color: '#FCA5A5',
    fontSize: 10,
    lineHeight: 14,
    marginTop: 4,
  },
  pwActionRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  pwActionBtn: {
    flex: 1,
    marginTop: 0,
  },
  pwHintOptional: {
    color: '#6A6A7D',
    fontSize: 9,
    fontWeight: '500',
  },
  removeLockBannerActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 12,
  },
  removeLockCancelBtn: {
    flex: 1,
    paddingVertical: 11,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: '#262638',
  },
  removeLockCancelText: {
    color: '#8A8A9D',
    fontSize: 11,
    fontWeight: '700',
  },
  removeLockConfirmBtn: {
    flex: 1,
    paddingVertical: 11,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(239, 68, 68, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.45)',
  },
  removeLockConfirmText: {
    color: '#FCA5A5',
    fontSize: 11,
    fontWeight: '800',
  },
  passwordErrorText: {
    color: '#FCA5A5',
  },
  passwordInlineError: {
    color: '#FCA5A5',
    fontSize: 10,
    fontWeight: '700',
    marginTop: -4,
    marginBottom: 10,
  },
  apiLockOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    zIndex: 20,
    elevation: 20,
    backgroundColor: 'rgba(5, 5, 8, 0.92)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
  },
  apiLockCard: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: '#0C0C12',
    borderWidth: 1,
    borderColor: 'rgba(123, 47, 255, 0.35)',
    borderRadius: 14,
    padding: 18,
    shadowColor: C.purple,
    shadowOpacity: 0.28,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 0 },
    elevation: 12,
  },
  apiLockCloseBtn: {
    position: 'absolute',
    top: 12,
    right: 12,
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#141420',
    borderWidth: 1,
    borderColor: '#262638',
    zIndex: 2,
  },
  apiLockIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(123, 47, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(123, 47, 255, 0.38)',
    marginBottom: 14,
  },
  apiLockTitle: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '900',
    marginBottom: 6,
    paddingRight: 34,
  },
  apiLockSub: {
    color: '#A8A8B8',
    fontSize: 11,
    lineHeight: 16,
    marginBottom: 16,
  },
  apiLockHintBanner: {
    backgroundColor: 'rgba(123, 47, 255, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(123, 47, 255, 0.32)',
    borderRadius: 10,
    padding: 10,
    marginBottom: 12,
  },
  apiLockHintTitle: {
    color: '#A78BFA',
    fontSize: 10,
    fontWeight: '900',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  apiLockHintText: {
    color: '#C4B5FD',
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '600',
  },
  apiLockUnlockBtn: {
    backgroundColor: C.purple,
    borderRadius: 8,
    paddingVertical: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // ─── Agent Library Panel ───────────────────────────
  agentLibraryPanelToggleOpen: {
    borderColor: 'rgba(123, 47, 255, 0.45)',
    backgroundColor: 'rgba(123, 47, 255, 0.06)',
  },
  agentLibraryIconBox: {
    backgroundColor: 'rgba(123, 47, 255, 0.1)',
    borderColor: 'rgba(123, 47, 255, 0.3)',
  },
  agentLibraryPanelStatePillOpen: {
    backgroundColor: 'rgba(123, 47, 255, 0.12)',
    borderColor: 'rgba(123, 47, 255, 0.45)',
  },
  agentLibraryPanelStateTextOpen: {
    color: C.purpleSoft,
  },
  agentLibraryPanel: {
    backgroundColor: '#0C0C12',
    borderWidth: 1,
    borderColor: '#20202F',
    borderRadius: 14,
    padding: 4,
    marginTop: -4,
    marginBottom: 16,
  },
  agentLibraryHero: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 14,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#1A1A28',
  },
  agentLibraryHeroIcon: {
    width: 40,
    height: 40,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(123, 47, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(123, 47, 255, 0.3)',
  },
  agentLibraryHeroTitle: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  agentLibraryHeroSub: {
    color: '#8A8A9D',
    fontSize: 10,
    marginTop: 2,
    lineHeight: 14,
  },
  agentLibraryActivePill: {
    backgroundColor: 'rgba(123, 47, 255, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(123, 47, 255, 0.35)',
    borderRadius: 7,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  agentLibraryActivePillText: {
    color: C.purpleSoft,
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 0.4,
  },
  agentLibraryGrid: {
    gap: 10,
  },
  teamAccordionGroup: {
    marginBottom: 10,
  },
  teamAccordionCard: {
    backgroundColor: '#11111A',
    borderWidth: 1.5,
    borderColor: '#20202F',
    borderRadius: 12,
    overflow: 'hidden',
  },
  teamAccordionCardActive: {
    borderColor: 'rgba(123, 47, 255, 0.45)',
  },
  teamAccordionCardExpanded: {
    borderColor: 'rgba(123, 47, 255, 0.35)',
  },
  teamAccordionHeader: {
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#141422',
  },
  teamAccordionHeaderActive: {
    backgroundColor: 'rgba(123, 47, 255, 0.06)',
  },
  teamAccordionIcon: {
    fontSize: 20,
    width: 28,
    textAlign: 'center',
  },
  teamAccordionTitle: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  teamAccordionSub: {
    color: '#8A8A9D',
    fontSize: 9,
    marginTop: 2,
  },
  teamBriefDesc: {
    color: '#8A8A9D',
    fontSize: 10,
    lineHeight: 14,
    marginTop: 10,
    marginBottom: 8,
  },
  teamAccordionPill: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    minWidth: 52,
    alignItems: 'center',
  },
  teamAccordionPillText: {
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 0.4,
  },
  teamPanelSwitchGlow: {
    borderRadius: 15,
    shadowColor: '#7B2FFF',
    shadowOpacity: 0.62,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 0 },
    elevation: 10,
  },
  teamPanelSwitch: {
    width: 46,
    height: 26,
    borderRadius: 13,
    padding: 3,
    backgroundColor: 'rgba(123, 47, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(123, 47, 255, 0.45)',
    justifyContent: 'center',
  },
  teamPanelSwitchActive: {
    backgroundColor: 'rgba(123, 47, 255, 0.22)',
    borderColor: 'rgba(167, 139, 250, 0.75)',
  },
  teamPanelSwitchKnob: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#74748A',
  },
  teamPanelSwitchKnobActive: {
    alignSelf: 'flex-end',
    backgroundColor: '#A78BFA',
  },
  teamAccordionBody: {
    padding: 14,
    backgroundColor: '#0C0C12',
    borderTopWidth: 1,
    borderTopColor: '#1B1B2A',
  },
  teamBodyIntro: {
    color: '#8A8A9D',
    fontSize: 10,
    lineHeight: 15,
    marginBottom: 14,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#1A1A28',
  },
  teamAgentRow: {
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#181824',
  },
  teamAgentRowLast: {
    marginBottom: 0,
    paddingBottom: 0,
    borderBottomWidth: 0,
  },
  teamAgentSlotLabel: {
    color: C.purpleSoft,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  teamAgentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 8,
  },
  teamAgentIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  teamAgentIcon: {
    fontSize: 16,
  },
  teamAgentName: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
  },
  teamAgentRole: {
    color: '#6A6A7D',
    fontSize: 9,
    marginTop: 1,
  },
  teamAgentFeatures: {
    marginLeft: 4,
    gap: 4,
  },
  teamAgentFeatureLine: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
  },
  teamAgentFeatureBullet: {
    color: '#5A5A6D',
    fontSize: 10,
    lineHeight: 14,
    width: 10,
  },
  teamAgentFeatureText: {
    color: '#9A9AAD',
    fontSize: 10,
    lineHeight: 14,
    flex: 1,
  },
  teamActivateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 14,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: '#1B1B2A',
  },
  teamActivateTitle: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '800',
  },
  teamActivateSub: {
    color: '#6A6A7D',
    fontSize: 9,
    marginTop: 2,
  },
  teamActivateMiniBtn: {
    minWidth: 92,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: 'rgba(34, 197, 94, 0.45)',
    backgroundColor: 'rgba(34, 197, 94, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  teamActivateMiniBtnText: {
    color: '#86EFAC',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.4,
  },
  teamDeactivateBtn: {
    minWidth: 104,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.5)',
    backgroundColor: 'rgba(239, 68, 68, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  teamDeactivateBtnText: {
    color: '#FCA5A5',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.4,
  },
  agentLibraryCard: {
    backgroundColor: '#11111A',
    borderWidth: 1,
    borderColor: '#222232',
    borderRadius: 12,
    padding: 12,
    overflow: 'hidden',
  },
  agentLibraryCardActive: {
    borderColor: 'rgba(123, 47, 255, 0.55)',
    backgroundColor: 'rgba(123, 47, 255, 0.05)',
  },
  agentLibraryCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  agentLibraryCardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  agentLibraryTeamIcon: {
    fontSize: 18,
  },
  agentLibraryCardTitle: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  agentLibraryCardTagline: {
    color: '#9A9AAD',
    fontSize: 9,
    marginTop: 1,
  },
  agentLibraryBadge: {
    borderRadius: 5,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderWidth: 1,
  },
  agentLibraryBadgeText: {
    fontSize: 7,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  agentLibraryCardDesc: {
    color: '#7A7A8D',
    fontSize: 10,
    lineHeight: 14,
    marginBottom: 10,
  },
  agentLibraryRoster: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  agentLibraryRosterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderWidth: 1,
    borderColor: '#252535',
    borderRadius: 7,
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  agentLibraryRosterIcon: {
    fontSize: 10,
  },
  agentLibraryRosterName: {
    color: '#C8C8D8',
    fontSize: 9,
    fontWeight: '600',
  },
  agentLibraryRosterSlot: {
    color: '#5A5A6D',
    fontSize: 8,
    fontWeight: '700',
  },
  agentLibrarySelectBtn: {
    marginTop: 10,
    borderRadius: 8,
    paddingVertical: 9,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#333344',
    backgroundColor: 'rgba(255,255,255,0.02)',
  },
  agentLibrarySelectBtnActive: {
    borderColor: 'rgba(123, 47, 255, 0.5)',
    backgroundColor: 'rgba(123, 47, 255, 0.12)',
  },
  agentLibrarySelectBtnText: {
    color: '#9A9AAD',
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  agentLibrarySelectBtnTextActive: {
    color: C.purpleSoft,
  },
};

export default settingsStyles;
